### ISSUE TITLE
Remove reacstrap as a dependency

### ISSUE THREAD

**Issue by juanjoseluisgarcia** [riyadelberkawy/formik-stepper#14]
Hi, 

reactstrap is overrrinding a copuple of my styles and it looks quite awful in dark mode. 

Can you remove reactstrap as a dependency and let us style the components ourselves?

**Comment by riyadelberkawy** [comment]
Hi Juan, thanks for your suggestion.

I want to tell you that the next minor release (soon) will remove reactstrap, but you can use your own input field by adding your custom component in inputField Props

you could check it [here](https://github.com/riyadelberkawy/formik-stepper#inputfield-props)

**Comment by juanjoseluisgarcia** [comment]
Hi Riya, 

The issue I have is that since it is a dependency it actually overrrides my global SCSS styles just by adding the library with yarn. So it is the whole app that gets messed up.

**Comment by riyadelberkawy** [comment]
Oh Sorry about that you gave me a reason to solve it ASAP
