### ISSUE TITLE
Formik Stepper submitting twice for some reason

### ISSUE THREAD

**Issue by ClintonEmok** [riyadelberkawy/formik-stepper#24]
I'm currently using formik-stepper and noticed it was submitting twice every single time I click on submit.
I went to the example on https://formik-stepper.web.app/ and noticed it happens here too.
Any proposed solution?

**Comment by riyadelberkawy** [comment]
Hi Clinton, Thanks for opening this issue.
I'll push the patch to fix this and some other bugs, by tomorrow at the latest :)

**Comment by riyadelberkawy** [comment]
Hi @ClintonEmok, you can update your version to the latest now  🚀
