### ISSUE TITLE
CSS Imported by a Dependency

### ISSUE THREAD

**Issue by novotny** [riyadelberkawy/formik-stepper#7]
Hi,

I have this error:

`./node_modules/formik-stepper/dist/inputFields/styles.min.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules\formik-stepper\dist\inputFields\InputField.js`

More info : #https://nextjs.org/docs/messages/css-npm

Any solution?

Thanks

**Comment by riyadelberkawy** [comment]
Hello Novotny :)

I'd like to let you know that I just published a new version at the moment.
I have deleted this file (/styles.min.css) and there is a new feature with which you can create your own input component

[check it out.](https://www.npmjs.com/package/formik-stepper)

Thanks.
